# Generated by Django 4.2.5 on 2024-12-29 13:25

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cab_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTODLOG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CList', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('startTime', models.DateTimeField(auto_now_add=True)),
                ('endTime', models.DateTimeField(blank=True, null=True)),
                ('return_start_time', models.TimeField(blank=True, null=True)),
                ('return_end_time', models.TimeField(blank=True, null=True)),
                ('tripDate', models.DateField(default=django.utils.timezone.now)),
                ('isActive', models.BooleanField(default=True, null=True)),
                ('batchId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cab_services.batch')),
            ],
        ),
    ]
