# Generated by Django 4.2.1 on 2023-07-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_servcies', '0003_delete_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subadmin',
            name='id',
            field=models.UUIDField(default='247c', editable=False, primary_key=True, serialize=False),
        ),
    ]
