# Generated by Django 4.2.1 on 2023-07-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchName', models.CharField(max_length=100)),
                ('batchTime', models.TimeField(null=True)),
                ('endDate', models.DateField(null=True)),
                ('startDate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='cab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regNumber', models.CharField(max_length=100, null=True)),
                ('capacity', models.IntegerField()),
                ('km', models.IntegerField()),
                ('regDate', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.BinaryField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pickUpPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickUpPointName', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routeName', models.CharField(max_length=100)),
            ],
        ),
    ]
