# Generated by Django 4.2.5 on 2024-12-29 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_servcies', '0001_initial'),
        ('cab_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='adminCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_servcies.subadmin'),
        ),
        migrations.AddField(
            model_name='pickuppoints',
            name='adminCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_servcies.subadmin'),
        ),
        migrations.AddField(
            model_name='pickuppoints',
            name='routeId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cab_services.routes'),
        ),
        migrations.AddField(
            model_name='cab',
            name='adminCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_servcies.subadmin'),
        ),
        migrations.AddField(
            model_name='cab',
            name='routeId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cab_services.routes'),
        ),
        migrations.AddField(
            model_name='batch',
            name='adminCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_servcies.subadmin'),
        ),
        migrations.AlterUniqueTogether(
            name='routes',
            unique_together={('routeName', 'adminCode')},
        ),
    ]
