# Generated by Django 4.2.1 on 2023-07-18 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cab_services', '0001_initial'),
        ('user_servcies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='adminCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_servcies.admin'),
        ),
        migrations.AddField(
            model_name='pickuppoints',
            name='adminCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_servcies.admin'),
        ),
        migrations.AddField(
            model_name='pickuppoints',
            name='routeId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cab_services.routes'),
        ),
        migrations.AddField(
            model_name='cab',
            name='adminCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_servcies.admin'),
        ),
        migrations.AddField(
            model_name='cab',
            name='routeId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cab_services.routes'),
        ),
        migrations.AddField(
            model_name='batch',
            name='adminCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_servcies.admin'),
        ),
    ]
