# Generated by Django 4.2.1 on 2023-07-18 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_servcies', '0002_remove_admin_userid_subadmin_and_more'),
        ('cab_services', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='adminCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_servcies.subadmin'),
        ),
        migrations.AlterField(
            model_name='cab',
            name='adminCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_servcies.subadmin'),
        ),
        migrations.AlterField(
            model_name='pickuppoints',
            name='adminCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_servcies.subadmin'),
        ),
        migrations.AlterField(
            model_name='routes',
            name='adminCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_servcies.subadmin'),
        ),
    ]
