# Generated by Django 4.2.1 on 2023-07-18 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_servcies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='userId',
        ),
        migrations.CreateModel(
            name='subAdmin',
            fields=[
                ('address', models.CharField(max_length=100, null=True)),
                ('id', models.UUIDField(default='edeb', editable=False, primary_key=True, serialize=False)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='commuter',
            name='adminCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_servcies.subadmin'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='adminCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_servcies.subadmin'),
        ),
    ]
