# Generated by Django 4.2.1 on 2023-07-18 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cab_services', '0003_alter_batch_admincode_alter_cab_admincode_and_more'),
        ('user_servcies', '0002_remove_admin_userid_subadmin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin',
        ),
    ]
