# Generated by Django 4.2.1 on 2023-07-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_servcies', '0006_alter_subadmin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subadmin',
            name='id',
            field=models.CharField(default='0a39', editable=False, max_length=4, primary_key=True, serialize=False),
        ),
    ]
